### ISSUE TITLE
when I try to generate in Salesforce a pdf, and then attach it (the error I get is BLOB is not a valid UTF-8 string)

### ISSUE THREAD

**Issue by motdotla** [motdotla/sendgrid-apex#1]
- https://developer.salesforce.com/forums/ForumsMain?id=906F00000008mCnIAI
- http://stackoverflow.com/questions/23749483/send-emails-with-attachments-in-salesforce-throw-sendgrid/23794434?noredirect=1#comment36603877_23794434

**Comment by bhaskararora** [comment]
+1

**Comment by mscoolmeenu** [comment]
+1

**Comment by Kavi667** [comment]
+1

**Comment by bhaskararora** [comment]
+1

**Comment by ReginaTrimble** [comment]
+1

**Comment by motdotla** [comment]
this repo was moved. closing.
